lints.workspace = true

[package]
name = "aoc-core"
description = "Advent of Code framework to structure solutions."
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
derive_more.workspace = true
proptest = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true

[features]
test = ["dep:proptest"]
