[workspace]
members = ["aoc/*", "years/year-2015"]
resolver = "3"

[workspace.lints]
clippy = { all = "deny" }
rust = { unsafe_code = "forbid" }

[workspace.package]
description = "Advent of Code proposition of solutions with Rust language."
authors = ["Swelio <swelio.github@outlook.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["education", "advent-of-code"]
repository = "https://github.com/Swelio/aoc-rs.git"
categories = ["advent-of-code"]

[profile.dev.build-override]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[patch.crates-io]
aoc-core = { path = "aoc/aoc-core" }
aoc-macros = { path = "aoc/aoc-macros" }
year-2015 = { path = "years/year-2015" }

[workspace.dependencies]
aoc-core = "0.1.0"
aoc-macros = "0.1.0"
year-2015 = "0.1.0"

anyhow = "1.0"
derive_more = { version = "2.0", features = ["full"] }
itertools = "0.14"
proptest = "1.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
winnow = "0.7"
