[workspace]
members = ["aoc/*"]
resolver = "3"

[workspace.lints]
clippy = { all = "deny" }
rust = { unsafe_code = "forbid" }

[workspace.package]
description = "Advent of Code proposition of solutions with Rust language."
authors = ["Swelio <swelio.github@outlook.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
keywords = ["education", "advent-of-code"]
repository = "https://github.com/Swelio/aoc-rs.git"
categories = ["advent-of-code"]

[profile.dev.build-override]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[workspace.dependencies]
