[package]
name = "year-2022"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
aoc-traits.workspace = true
nutype.workspace = true
winnow.workspace = true
