[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[lints]
clippy = { all = "deny" }
rust = { unsafe_code = "forbid" }

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
