lints.workspace = true

[package]
name = "year-2015"
description.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
aoc-core.workspace = true
aoc-macros.workspace = true

anyhow.workspace = true
derive_more.workspace = true
rayon.workspace = true
winnow.workspace = true

md-5 = "0.10.6"
regex = "1.11.1"

[dev-dependencies]
aoc-core = { workspace = true, features = ["test"] }
proptest.workspace = true
