name: Devcontainer prebuilding

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - .github/.devcontainer.json
  pull_request:
    branches:
      - 'main'
    paths:
      - .github/.devcontainer.json
  schedule:
    - cron: '59 23 * * FRI'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-build:
    uses: Swelio/continuous-integration/workflows/devcontainer-prebuild.yaml@main
