name: Lint checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt,clippy
      - name: Run rustfmt
        run: cargo +stable fmt -- --check
      - name: Run Clippy
        run: cargo +stable clippy --verbose -- -D warnings
      - name: Run Clippy on tests
        run: cargo +stable clippy --verbose --tests -- -D warnings